python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang fr --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang de --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang es --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang ca --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang it --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang ru --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang zh-CN --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang pt --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang fa --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang et --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang mn --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang nl --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang tr --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang ar --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang sv-SE --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang lv --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang sl --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang ta --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang ja --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang id --tgt-lang en
python mST/prepare_data/prep_covost_data.py --data-root $COVOST2_ROOT --src-lang cy --tgt-lang en